security:
    password_hashers:
        "Symfony\\Component\\Security\\Core\\User\\InMemoryUser":
            algorithm: bcrypt
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: "$2a$12$2IzOWygpqAUe1oPLMIIzPOQHHUuUL9gPLzsck9pKYvtsWj.C0Gzrq"
                        roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            http_basic: ~
    access_control:
        - { path: ^/crawl, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
